<a href="https://colab.research.google.com/github/masonsears/-Data-Processing-Visualization-CPSMA-4313-01-projects/blob/Projects/Exam3_MasonSears.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Exam 3 Mason Sears CPSMA-4313-01

In [10]:
import pandas as pa

## Part One

a.

In [11]:
df = pa.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/refs/heads/main/Data_Sets/Activity_Dataset_V1.csv')
df.head(30)

,Unnamed: 0,activity_day,workout_type,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,...,max_pace,min_pace,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max(%),aerobic(%),anaerobic(%),intensive(%),light(%)
0,0,2022-01-01,Freestyle,9.30,77,123,NaN,18.88,168.54,138.30,...,NaN,NaN,112.5,122.0,103,19,28,2,7,50
1,1,2022-01-01,Freestyle,3.44,96,55,NaN,29.65,125.92,292.81,...,NaN,NaN,111.0,122.0,100,42,28,2,29,88
2,2,2022-01-01,Indoor Cycling,6.34,85,33,NaN,17.85,81.93,323.69,...,NaN,NaN,95.0,90.0,100,1,32,0,22,43
3,3,2022-01-01,Walking,7.91,42,82,1571.0,22.10,29.63,180.16,...,28:58,07:58,83.0,85.0,81,3,22,0,24,65
4,4,2022-01-01,Open Water,8.99,36,131,NaN,25.83,64.55,342.89,...,NaN,NaN,138.0,166.0,110,7,0,5,21,88
5,5,2022-01-01,Outdoor Cycling,5.47,117,144,NaN,2.20,43.47,291.67,...,NaN,NaN,142.0,177.0,107,44,45,15,57,39
6,6,2022-01-01,Indoor Cycling,6.28,66,378,NaN,10.65,23.83,253.84,...,NaN,NaN,85.0,90.0,80,34,32,0,44,23
7,7,2022-01-01,Outdoor Running,2.94,26,430,7618.0,10.59,131.93,334.72,...,27:44,06:15,145.0,190.0,100,23,0,71,18,3
8,8,2022-01-01,Trail Run,2.87,26,465,2790.0,32.92,21.42,341.17,...,25:50,06:20,142.0,188.0,96,2,0,80,46,13
9,9,2022-01-01,Pool Swimming,3.91,23,99,NaN,33.15,169.30,206.97,...,NaN,NaN,132.5,175.0,90,22,20,15,28,20
10,10,2022-01-01,Trail Run,6.31,107,97,2790.0,22.99,27.99,139.21,...,25:50,06:20,138.5,188.0,89,38,0,80,13,16
11,11,2022-01-01,Outdoor Running,2.37,65,524,7618.0,16.47,164.78,87.60,...,27:44,06:15,146.0,190.0,102,17,0,71,46,12
12,12,2022-01-01,Indoor Cycling,3.50,43,158,NaN,12.54,25.36,184.20,...,NaN,NaN,99.0,90.0,108,21,32,0,24,59
13,13,2022-01-01,Outdoor Cycling,1.86,111,195,NaN,19.95,15.99,317.51,...,NaN,NaN,134.5,177.0,92,26,45,15,64,84
14,14,2022-01-01,Freestyle,8.41,70,412,NaN,35.93,113.85,262.50,...,NaN,NaN,115.0,122.0,108,36,28,2,28,63
15,15,2022-01-01,Open Water,6.77,102,333,NaN,11.46,155.72,201.74,...,NaN,NaN,123.0,166.0,80,43,0,5,22,18
16,16,2022-01-01,Trekking,5.69,78,248,5028.0,3.22,47.35,321.79,...,24:45,07:45,108.5,124.0,93,19,50,0,23,96
17,17,2022-01-01,Trekking,6.54,118,496,5028.0,2.99,87.50,135.87,...,24:45,07:45,113.0,124.0,102,17,50,0,63,37
18,18,2022-01-01,Treadmill,1.89,108,150,4550.0,31.49,69.99,198.70,...,27:58,07:58,103.0,105.0,101,26,26,7,46,64
19,19,2022-01-01,Open Water,1.48,47,441,NaN,26.49,136.32,206.15,...,NaN,NaN,131.0,166.0,96,0,0,5,63,61
20,20,2022-01-01,Indoor Cycling,2.21,90,377,NaN,8.73,164.42,163.67,...,NaN,NaN,95.5,90.0,101,38,32,0,64,32
21,21,2022-01-01,Open Water,9.45,76,72,NaN,17.58,197.28,315.25,...,NaN,NaN,124.5,166.0,83,22,0,5,56,71
22,22,2022-01-01,Cricket,2.78,41,25,3444.0,29.89,126.56,129.14,...,22:02,07:02,95.5,92.0,99,6,40,10,35,56
23,23,2022-01-01,Treadmill,5.66,76,368,4550.0,20.14,160.37,261.85,...,27:58,07:58,104.0,105.0,103,7,26,7,38,34
24,24,2022-01-01,Cricket,3.71,92,343,3444.0,29.29,12.28,230.99,...,22:02,07:02,87.0,92.0,82,33,40,10,49,80
25,25,2022-01-01,Cricket,6.52,59,467,3444.0,26.87,59.96,205.40,...,22:02,07:02,101.0,92.0,110,20,40,10,35,94
26,26,2022-01-01,Outdoor Running,6.41,40,377,7618.0,19.67,75.95,255.54,...,27:44,06:15,138.5,190.0,87,38,0,71,45,88
27,27,2022-01-01,Cricket,3.95,88,277,3444.0,20.89,46.50,269.71,...,22:02,07:02,91.5,92.0,91,18,40,10,50,55
28,28,2022-01-02,Cricket,8.23,91,416,3444.0,23.83,116.62,88.80,...,22:02,07:02,87.0,92.0,82,5,40,10,34,25
29,29,2022-01-02,Treadmill,1.71,77,356,4550.0,19.16,105.43,111.24,...,27:58,07:58,93.0,105.0,81,43,26,7,46,39

In [12]:
df.dtypes

Unnamed: 0          int64
activity_day       object
workout_type       object
distance          float64
time                int64
calories            int64
total_steps       float64
avg_speed         float64
avg_cadence       float64
max_cadence       float64
avg_pace           object
max_pace           object
min_pace           object
avg_heart_rate    float64
max_heart_rate    float64
min_heart_rate      int64
vo2_max(%)          int64
aerobic(%)          int64
anaerobic(%)        int64
intensive(%)        int64
light(%)            int64
dtype: object

max_heart_rate and min_heart_rate shopuld be integers instead of floats because none of them are floats.

In [13]:
df['max_heart_rate'] = df['max_heart_rate'].astype(int)
df.dtypes

Unnamed: 0          int64
activity_day       object
workout_type       object
distance          float64
time                int64
calories            int64
total_steps       float64
avg_speed         float64
avg_cadence       float64
max_cadence       float64
avg_pace           object
max_pace           object
min_pace           object
avg_heart_rate    float64
max_heart_rate      int64
min_heart_rate      int64
vo2_max(%)          int64
aerobic(%)          int64
anaerobic(%)        int64
intensive(%)        int64
light(%)            int64
dtype: object

This makes it easier to look at

b.

In [14]:
df = df.drop('Unnamed: 0', axis=1)
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")
/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,activity_day,workout_type,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_pace,max_pace,min_pace,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max(%),aerobic(%),anaerobic(%),intensive(%),light(%)
0,2022-01-01,Freestyle,9.30,77,123,NaN,18.88,168.54,138.30,NaN,NaN,NaN,112.5,122,103,19,28,2,7,50
1,2022-01-01,Freestyle,3.44,96,55,NaN,29.65,125.92,292.81,NaN,NaN,NaN,111.0,122,100,42,28,2,29,88
2,2022-01-01,Indoor Cycling,6.34,85,33,NaN,17.85,81.93,323.69,NaN,NaN,NaN,95.0,90,100,1,32,0,22,43
3,2022-01-01,Walking,7.91,42,82,1571.0,22.10,29.63,180.16,07:58,28:58,07:58,83.0,85,81,3,22,0,24,65
4,2022-01-01,Open Water,8.99,36,131,NaN,25.83,64.55,342.89,NaN,NaN,NaN,138.0,166,110,7,0,5,21,88

this one gave me a headache for no reason because i ran it multiple times and broke it.

c.

In [15]:
df.columns = df.columns.str.replace('(%)', '', regex=False).str.replace(' ', '', regex=False)
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")
/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,activity_day,workout_type,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_pace,max_pace,min_pace,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max,aerobic,anaerobic,intensive,light
0,2022-01-01,Freestyle,9.30,77,123,NaN,18.88,168.54,138.30,NaN,NaN,NaN,112.5,122,103,19,28,2,7,50
1,2022-01-01,Freestyle,3.44,96,55,NaN,29.65,125.92,292.81,NaN,NaN,NaN,111.0,122,100,42,28,2,29,88
2,2022-01-01,Indoor Cycling,6.34,85,33,NaN,17.85,81.93,323.69,NaN,NaN,NaN,95.0,90,100,1,32,0,22,43
3,2022-01-01,Walking,7.91,42,82,1571.0,22.10,29.63,180.16,07:58,28:58,07:58,83.0,85,81,3,22,0,24,65
4,2022-01-01,Open Water,8.99,36,131,NaN,25.83,64.55,342.89,NaN,NaN,NaN,138.0,166,110,7,0,5,21,88

In [16]:
df.dtypes

activity_day       object
workout_type       object
distance          float64
time                int64
calories            int64
total_steps       float64
avg_speed         float64
avg_cadence       float64
max_cadence       float64
avg_pace           object
max_pace           object
min_pace           object
avg_heart_rate    float64
max_heart_rate      int64
min_heart_rate      int64
vo2_max             int64
aerobic             int64
anaerobic           int64
intensive           int64
light               int64
dtype: object

looks much more uniform

d.

In [18]:
df['activity_day'] = pa.to_datetime(df['activity_day'])
df.dtypes

activity_day      datetime64[ns]
workout_type              object
distance                 float64
time                       int64
calories                   int64
total_steps              float64
avg_speed                float64
avg_cadence              float64
max_cadence              float64
avg_pace                  object
max_pace                  object
min_pace                  object
avg_heart_rate           float64
max_heart_rate             int64
min_heart_rate             int64
vo2_max                    int64
aerobic                    int64
anaerobic                  int64
intensive                  int64
light                      int64
dtype: object

In [20]:
df.head(30)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")
/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,activity_day,workout_type,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_pace,max_pace,min_pace,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max,aerobic,anaerobic,intensive,light
0,2022-01-01,Freestyle,9.30,77,123,NaN,18.88,168.54,138.30,NaN,NaN,NaN,112.5,122,103,19,28,2,7,50
1,2022-01-01,Freestyle,3.44,96,55,NaN,29.65,125.92,292.81,NaN,NaN,NaN,111.0,122,100,42,28,2,29,88
2,2022-01-01,Indoor Cycling,6.34,85,33,NaN,17.85,81.93,323.69,NaN,NaN,NaN,95.0,90,100,1,32,0,22,43
3,2022-01-01,Walking,7.91,42,82,1571.0,22.10,29.63,180.16,07:58,28:58,07:58,83.0,85,81,3,22,0,24,65
4,2022-01-01,Open Water,8.99,36,131,NaN,25.83,64.55,342.89,NaN,NaN,NaN,138.0,166,110,7,0,5,21,88
5,2022-01-01,Outdoor Cycling,5.47,117,144,NaN,2.20,43.47,291.67,NaN,NaN,NaN,142.0,177,107,44,45,15,57,39
6,2022-01-01,Indoor Cycling,6.28,66,378,NaN,10.65,23.83,253.84,NaN,NaN,NaN,85.0,90,80,34,32,0,44,23
7,2022-01-01,Outdoor Running,2.94,26,430,7618.0,10.59,131.93,334.72,06:44,27:44,06:15,145.0,190,100,23,0,71,18,3
8,2022-01-01,Trail Run,2.87,26,465,2790.0,32.92,21.42,341.17,06:48,25:50,06:20,142.0,188,96,2,0,80,46,13
9,2022-01-01,Pool Swimming,3.91,23,99,NaN,33.15,169.30,206.97,NaN,NaN,NaN,132.5,175,90,22,20,15,28,20
10,2022-01-01,Trail Run,6.31,107,97,2790.0,22.99,27.99,139.21,06:48,25:50,06:20,138.5,188,89,38,0,80,13,16
11,2022-01-01,Outdoor Running,2.37,65,524,7618.0,16.47,164.78,87.60,06:44,27:44,06:15,146.0,190,102,17,0,71,46,12
12,2022-01-01,Indoor Cycling,3.50,43,158,NaN,12.54,25.36,184.20,NaN,NaN,NaN,99.0,90,108,21,32,0,24,59
13,2022-01-01,Outdoor Cycling,1.86,111,195,NaN,19.95,15.99,317.51,NaN,NaN,NaN,134.5,177,92,26,45,15,64,84
14,2022-01-01,Freestyle,8.41,70,412,NaN,35.93,113.85,262.50,NaN,NaN,NaN,115.0,122,108,36,28,2,28,63
15,2022-01-01,Open Water,6.77,102,333,NaN,11.46,155.72,201.74,NaN,NaN,NaN,123.0,166,80,43,0,5,22,18
16,2022-01-01,Trekking,5.69,78,248,5028.0,3.22,47.35,321.79,07:55,24:45,07:45,108.5,124,93,19,50,0,23,96
17,2022-01-01,Trekking,6.54,118,496,5028.0,2.99,87.50,135.87,07:55,24:45,07:45,113.0,124,102,17,50,0,63,37
18,2022-01-01,Treadmill,1.89,108,150,4550.0,31.49,69.99,198.70,07:59,27:58,07:58,103.0,105,101,26,26,7,46,64
19,2022-01-01,Open Water,1.48,47,441,NaN,26.49,136.32,206.15,NaN,NaN,NaN,131.0,166,96,0,0,5,63,61
20,2022-01-01,Indoor Cycling,2.21,90,377,NaN,8.73,164.42,163.67,NaN,NaN,NaN,95.5,90,101,38,32,0,64,32
21,2022-01-01,Open Water,9.45,76,72,NaN,17.58,197.28,315.25,NaN,NaN,NaN,124.5,166,83,22,0,5,56,71
22,2022-01-01,Cricket,2.78,41,25,3444.0,29.89,126.56,129.14,07:015,22:02,07:02,95.5,92,99,6,40,10,35,56
23,2022-01-01,Treadmill,5.66,76,368,4550.0,20.14,160.37,261.85,07:59,27:58,07:58,104.0,105,103,7,26,7,38,34
24,2022-01-01,Cricket,3.71,92,343,3444.0,29.29,12.28,230.99,07:015,22:02,07:02,87.0,92,82,33,40,10,49,80
25,2022-01-01,Cricket,6.52,59,467,3444.0,26.87,59.96,205.40,07:015,22:02,07:02,101.0,92,110,20,40,10,35,94
26,2022-01-01,Outdoor Running,6.41,40,377,7618.0,19.67,75.95,255.54,06:44,27:44,06:15,138.5,190,87,38,0,71,45,88
27,2022-01-01,Cricket,3.95,88,277,3444.0,20.89,46.50,269.71,07:015,22:02,07:02,91.5,92,91,18,40,10,50,55
28,2022-01-02,Cricket,8.23,91,416,3444.0,23.83,116.62,88.80,07:015,22:02,07:02,87.0,92,82,5,40,10,34,25
29,2022-01-02,Treadmill,1.71,77,356,4550.0,19.16,105.43,111.24,07:59,27:58,07:58,93.0,105,81,43,26,7,46,39

i thought broke it because it was all the same date.

e.

In [21]:
df = df.fillna(0)
df.head()

,activity_day,workout_type,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_pace,max_pace,min_pace,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max,aerobic,anaerobic,intensive,light
0,2022-01-01,Freestyle,9.30,77,123,0.0,18.88,168.54,138.30,0,0,0,112.5,122,103,19,28,2,7,50
1,2022-01-01,Freestyle,3.44,96,55,0.0,29.65,125.92,292.81,0,0,0,111.0,122,100,42,28,2,29,88
2,2022-01-01,Indoor Cycling,6.34,85,33,0.0,17.85,81.93,323.69,0,0,0,95.0,90,100,1,32,0,22,43
3,2022-01-01,Walking,7.91,42,82,1571.0,22.10,29.63,180.16,07:58,28:58,07:58,83.0,85,81,3,22,0,24,65
4,2022-01-01,Open Water,8.99,36,131,0.0,25.83,64.55,342.89,0,0,0,138.0,166,110,7,0,5,21,88

f.

In [22]:
calories_stats = df.groupby('workout_type')['calories'].agg(['mean', 'median', 'count', 'std'])
display(calories_stats)

                       mean  median  count         std
workout_type
Cricket          307.548387   330.0     93  149.950609
Freestyle        278.552083   294.0     96  163.703768
Indoor Cycling   280.450000   306.0     80  156.633322
Open Water       296.747253   328.0     91  160.068499
Outdoor Cycling  299.129412   301.0     85  158.731263
Outdoor Running  301.469136   349.0     81  165.725080
Pool Swimming    283.414894   300.0     94  157.576703
Trail Run        267.966667   264.0     90  155.748533
Treadmill        278.142857   269.5     98  146.963352
Trekking         283.127660   280.5     94  151.034870
Walking          276.040816   270.5     98  157.287570

Cricket burns a lot fo calories compared to the other workout types.

h.

In [23]:
df['aerobic_30_percent_plus'] = df['aerobic'] >= 30
display(df.head())

,activity_day,workout_type,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_pace,...,min_pace,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max,aerobic,anaerobic,intensive,light,aerobic_30_percent_plus
0,2022-01-01,Freestyle,9.30,77,123,0.0,18.88,168.54,138.30,0,...,0,112.5,122,103,19,28,2,7,50,False
1,2022-01-01,Freestyle,3.44,96,55,0.0,29.65,125.92,292.81,0,...,0,111.0,122,100,42,28,2,29,88,False
2,2022-01-01,Indoor Cycling,6.34,85,33,0.0,17.85,81.93,323.69,0,...,0,95.0,90,100,1,32,0,22,43,True
3,2022-01-01,Walking,7.91,42,82,1571.0,22.10,29.63,180.16,07:58,...,07:58,83.0,85,81,3,22,0,24,65,False
4,2022-01-01,Open Water,8.99,36,131,0.0,25.83,64.55,342.89,0,...,0,138.0,166,110,7,0,5,21,88,False

i.

In [25]:
df['day_of_week'] = df['activity_day'].dt.day_name()

max_cadence_by_day_workout = df.groupby(['day_of_week', 'workout_type'])['max_cadence'].max()

max_cadence_overall = max_cadence_by_day_workout.idxmax()
max_cadence_value = max_cadence_by_day_workout.max()

display(f"Day and Workout Type: {max_cadence_overall}")
display(f"Max Cadence: {max_cadence_value}")

"Day of Week and Workout Type: ('Wednesday', 'Pool Swimming')"

'Max Cadence Value: 349.78'

## Part Two

a.
The only query i made was "Find the mean, median, count, and standard deviation of calories" because i forgot what the command for them were.

b. It did exactly what i wanted it to do so i accepted it.

c. I used the study guide to prepare for the exam. And i had to google how to drop of column because i was struggling with it because i kept trying to run the command without reseting the kernal.



*   https://github.com/nurfnick/Data_Viz/blob/main/Content/Data_Cleaning/Exam3Review.ipynb
*   https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

d. I attest that the resources above were the only ones utilized in completing
the exam and the work included is my own and no one else from the course.